---
- name: Deploy Static Web Page
  hosts: group
  become: true
  tasks:
    - name: "Install Apache"
      apt:
        name: apache2
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: "Install Apache"
      yum:
        name: httpd
        update_cache: true
      when: ansible_distribution == "Amazon"

    - name: "Start Apache"
      service:
        name: httpd
        state: started
      when: ansible_distribution == "Amazon"

    - name: "Copy Static file"
      copy:
        src: static.html
        dest: /var/www/html
        force: true
